# Generated by Django 4.1.3 on 2022-11-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalibrator_listesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter kodu')),
                ('inventory_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter tipi')),
                ('inventory_sub_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter alt tipi')),
                ('device_brand', models.CharField(blank=True, max_length=200, null=True, verbose_name='marka')),
                ('device_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='seri numarası')),
                ('period_of_validity', models.DateField(blank=True, null=True, verbose_name='geçerlilik süresi')),
                ('traceability', models.CharField(blank=True, max_length=200, null=True, verbose_name='izlenebilirlik')),
            ],
            options={
                'verbose_name': 'kalibratör listesi',
                'verbose_name_plural': 'kalibratör listesi',
            },
        ),
        migrations.CreateModel(
            name='Sablon_Adı',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='şablon adı')),
            ],
            options={
                'verbose_name': 'şablon adı',
                'verbose_name_plural': 'şablon adı',
            },
        ),
        migrations.CreateModel(
            name='Sablon_olustur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Test adı')),
                ('set_test', models.CharField(choices=[('text', 'text'), ('checkbox', 'checkbox')], max_length=200, verbose_name='ayarlanan')),
                ('measurement_result', models.CharField(choices=[('text', 'text'), ('checkbox', 'checkbox')], max_length=200, verbose_name='ölçüm sonucu')),
                ('template_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalibrasyonApp.sablon_adı')),
            ],
            options={
                'verbose_name': 'şablon oluştur',
                'verbose_name_plural': 'şablon oluştur',
            },
        ),
        migrations.CreateModel(
            name='Gorev_listesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(error_messages={'unique': 'Görev numarası benzersiz olmalı'}, max_length=200, unique=True, verbose_name='görev numarası')),
                ('inventory_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter kodu')),
                ('inventory_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter tipi')),
                ('inventory_sub_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter alt tipi')),
                ('device_brand', models.CharField(blank=True, max_length=200, null=True, verbose_name='marka')),
                ('device_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='seri numarası')),
                ('task_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='görev tipi')),
                ('task_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='görev adı')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='plan tarih')),
                ('task_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='görev durumu')),
                ('explanation', models.CharField(blank=True, max_length=200, null=True, verbose_name='açıklama')),
                ('liable_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='sorumlu tipi')),
                ('responsible', models.CharField(blank=True, max_length=200, null=True, verbose_name='sorumlu kişi')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='tamamlama tarih')),
                ('branch', models.CharField(blank=True, max_length=200, null=True, verbose_name='şube')),
                ('branch_building', models.CharField(blank=True, max_length=200, null=True, verbose_name='bina')),
                ('building_floor', models.CharField(blank=True, max_length=200, null=True, verbose_name='kat')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='konum')),
                ('person_doing', models.CharField(blank=True, max_length=200, null=True, verbose_name='yapan kişi')),
                ('label', models.BooleanField(blank=True, null=True, verbose_name='etiket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'görev listesi',
                'verbose_name_plural': 'görev listesi',
            },
        ),
        migrations.CreateModel(
            name='Finished_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_times', models.DateTimeField(blank=True, null=True, verbose_name='Test süresi')),
                ('device_image', models.ImageField(blank=True, max_length=200, null=True, upload_to='deviceImage')),
                ('test_header', models.CharField(blank=True, max_length=200, null=True, verbose_name='Test başlığı')),
                ('measurement_result', models.JSONField(blank=True, null=True, verbose_name='Ölçüm sonucu')),
                ('Finished_task', models.OneToOneField(blank=True, default=500, null=True, on_delete=django.db.models.deletion.PROTECT, to='kalibrasyonApp.gorev_listesi')),
            ],
            options={
                'verbose_name': 'Biten iş',
                'verbose_name_plural': 'Biten iş',
            },
        ),
    ]
