# Generated by Django 4.1.3 on 2022-11-04 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kalibrasyonApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_task',
            name='Finished_task',
        ),
        migrations.AddField(
            model_name='finished_task',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='şube'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='branch_building',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='bina'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='building_floor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='kat'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='tamamlama tarih'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='device_brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='marka'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='device_model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='explanation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter kodu'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='inventory_sub_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter alt tipi'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='inventory_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='envanter tipi'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='label',
            field=models.BooleanField(blank=True, null=True, verbose_name='etiket'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='liable_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sorumlu tipi'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='konum'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='person_doing',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='yapan kişi'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='plan tarih'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='responsible',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sorumlu kişi'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='seri numarası'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='task_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='görev adı'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='task_number',
            field=models.CharField(default=datetime.datetime(2022, 11, 4, 12, 54, 3, 976731, tzinfo=datetime.timezone.utc), error_messages={'unique': 'Görev numarası benzersiz olmalı'}, max_length=200, unique=True, verbose_name='görev numarası'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finished_task',
            name='task_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='görev durumu'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='task_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='görev tipi'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
