# Generated by Django 4.1.3 on 2022-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0002_remove_finished_task_finished_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_task',
            name='device_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='deviceImage/'),
        ),
    ]
