# Generated by Django 4.1.3 on 2022-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0006_alter_finished_task_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sablon_olustur',
            name='set_test',
            field=models.CharField(max_length=200, verbose_name='ayarlanan'),
        ),
    ]
