# Generated by Django 4.1.6 on 2023-02-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0008_sablon_olustur_calibrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sablon_adı',
            name='calibrator',
            field=models.ManyToManyField(to='kalibrasyonApp.kalibrator_listesi'),
        ),
    ]
