# Generated by Django 4.1.6 on 2023-02-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0009_sablon_adı_calibrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sablon_olustur',
            name='calibrator',
        ),
    ]
