# Generated by Django 4.1.6 on 2023-02-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0010_remove_sablon_olustur_calibrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sablon_adı',
            name='template_test',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
