# Generated by Django 4.1.7 on 2023-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0011_sablon_adı_template_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_task',
            name='test_times',
        ),
        migrations.AddField(
            model_name='finished_task',
            name='test_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test başlangıç tarihi'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='test_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test başlangıç tarihi'),
        ),
    ]
