# Generated by Django 4.1.7 on 2023-03-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0012_remove_finished_task_test_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_task',
            name='test_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test bitiş tarihi'),
        ),
    ]
