# Generated by Django 4.1.7 on 2023-03-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0013_alter_finished_task_test_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_task',
            name='test_header',
        ),
    ]
