# Generated by Django 4.1.7 on 2023-03-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0015_alter_finished_task_test_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_task',
            name='calibratorData',
            field=models.JSONField(blank=True, null=True, verbose_name='Kalibratör datası'),
        ),
        migrations.AddField(
            model_name='finished_task',
            name='functionTest',
            field=models.JSONField(blank=True, null=True, verbose_name='Fonksiyon Testi'),
        ),
    ]
