# Generated by Django 4.1.7 on 2023-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalibrasyonApp', '0017_sablon_olustur_set_test_two_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sablon_olustur',
            name='set_test_two',
        ),
        migrations.AlterField(
            model_name='sablon_olustur',
            name='measurement_result',
            field=models.CharField(choices=[('text', 'text'), ('checkbox', 'checkbox')], max_length=200, verbose_name='ölçüm sonucu'),
        ),
    ]
